Debug: 0
Mode: 0

OutputFolder: output

StartNode: 260a2000
EndNode: 260a2003
NodeList:
  - 260A0365
  - 260A1859
  - 260A0369
  - 260A1790
BlacklistNodes:

StartTimestamp:
  Year: 2022
  Month: 07
  Day: 11
  Hour: 08

EndTimestamp:
  Year: 2022
  Month: 07
  Day: 12
  Hour: 08

Thingsboard:
  Host: http://ops.aoms-tech.com
  Port: 8080
  Username: hardware@aoms-tech.com
  Password: Zhr9byhcwMt_YZLPY!_ta@
  CustomerName: AOMS OPS