Debug: 0
Mode: 0

OutputFolder: output

StartNode: 260a2050
EndNode: 260a2079
NodeList:
BlacklistNodes:

StartTimestamp:
  Year: 2022
  Month: 06
  Day: 20

Thingsboard:
  Host: http://ops.aoms-tech.com
  Port: 8080
  Username: hardware@aoms-tech.com
  Password: Zhr9byhcwMt_YZLPY!_ta@
  CustomerName: AOMS OPS